sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QPiUv9WJ8Dq0VDIAU+iKW2pK5icBLm7QTombOgy1DTFygFrPFqiaN52RbLYp6M4WX5vx/Ov9ErNDBjdrB9NXu0DiPXnD/Jcv45tVsX0z65oVILneo1exUr6ITF8pDdHJwE29I9un18Tdu8mh8yg0vcKncOHfiMDfr4jqlr1LXkXE4ZPWthqeJpcm4IuomXbPk4xCz6Q9miRE2lopGfpgmhbcqMHjERPtV5vqdPHob2INF4O9idMfiHpARPXXvb7Nshcs7ersASW4rT1BuiP4DNxgfoK+vWhxCp/jcb0Qjb3tXB94HYRnlvpQah+UK9Ie3aOkqMeh3D5hEVkPe3bA5lg+6rQkth6hL6yEYkTWxPy351u5xs4sg1hImvG6sadJ0gSdKoeb4FUoosC7y00fvE8EYXKU5CUIWMFuk3sTw1wOupOE2/ffTVlt8kBO1R/YLKFGlz7lOVmtxVEgLgEkV3S8yGDtD6WOVXkRJDt8bIPPlsR6IcSZrZh/444w20h3CioPthtTyEEx6C8lOjCXJLzAPK3F/Au+Uj0sCbbZUFrrO1W2qc38aDNuDtNAmkBmhKSmMDKJFSoTprNAb7u6csyc7WIE0q9FkaTl9F5n6rnVJR0g4MdX57HRhl5kUbw3odam2jHZiCOmNO7Ue1Qr++QrStDfmkOO0zv6aDCJDYk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Fromont-and-Risler-Volume-4_3979
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy